apiVersion: v1
kind: ConfigMap
metadata:
  name: clickhouse-config
data:
  config.xml: |
    <yandex>
      <storage_configuration>
        <disks>
          <hot>
            <path>/var/lib/clickhouse/</path>
          </hot>
          <cold>
            <path>/var/lib/clickhouse/cold/</path>
          </cold>
        </disks>
        <policies>
          <hot_to_cold>
            <volumes>
              <main>
                <disk>hot</disk>
                <max_data_part_size_bytes>5368709120</max_data_part_size_bytes>
              </main>
              <external>
                <disk>cold</disk>
                <max_data_part_size_bytes>10737418240</max_data_part_size_bytes>
                <move_factor>0.2</move_factor>
              </external>
            </volumes>
          </hot_to_cold>
        </policies>
      </storage_configuration>
    </yandex>
