apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hot-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.hot.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cold-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.cold.size }}
